import React, { useState } from 'react';
import { Calculator, RotateCcw, TrendingUp, Target, DollarSign, ShoppingBag, Percent, ArrowRight } from 'lucide-react';

const DEFAULTS = {
  adSpend: 5000,
  revenue: 17500,
  orders: 250,
  cogsPercent: 30,
  otherCostPercent: 10
};

const money = (n) =>
  '$' + Math.round(n).toLocaleString('en-US');

const money2 = (n) =>
  '$' + (Math.round(n * 100) / 100).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function RoasCalculatorPage({ onOpenBooking }) {
  const [v, setV] = useState(DEFAULTS);

  const update = (key) => (e) => {
    const raw = e.target.value;
    setV((prev) => ({ ...prev, [key]: raw === '' ? '' : Math.max(0, Number(raw)) }));
  };
  const num = (key) => (v[key] === '' ? 0 : Number(v[key]));

  const adSpend = num('adSpend');
  const revenue = num('revenue');
  const orders = num('orders');
  const cogsPercent = Math.min(100, num('cogsPercent'));
  const otherCostPercent = Math.min(100, num('otherCostPercent'));

  const roas = adSpend > 0 ? revenue / adSpend : 0;
  const grossMarginPercent = Math.max(0, 100 - cogsPercent - otherCostPercent);
  const breakEvenRoas = grossMarginPercent > 0 ? 100 / grossMarginPercent : 0;
  const aov = orders > 0 ? revenue / orders : 0;
  const cpa = orders > 0 ? adSpend / orders : 0;
  const grossProfit = revenue * (grossMarginPercent / 100);
  const netProfit = grossProfit - adSpend;
  const netMargin = revenue > 0 ? (netProfit / revenue) * 100 : 0;
  const profitPerOrder = orders > 0 ? netProfit / orders : 0;
  const hasInput = adSpend > 0 && revenue > 0;

  let verdict = { label: 'Enter your numbers', tone: 'neutral', note: 'Fill in ad spend and revenue to see whether your campaigns are profitable.' };
  if (hasInput) {
    if (breakEvenRoas === 0) {
      verdict = { label: 'Margins too thin', tone: 'bad', note: 'Product and other costs consume 100% of revenue, so no ROAS can be profitable.' };
    } else if (roas >= breakEvenRoas * 1.25) {
      verdict = { label: 'Profitable, ready to scale', tone: 'good', note: `You are ${(roas / breakEvenRoas).toFixed(2)}x above break-even. Every $1 of ad spend returns ${money2(roas)} in revenue.` };
    } else if (roas >= breakEvenRoas) {
      verdict = { label: 'Profitable, but thin', tone: 'ok', note: 'You are above break-even with little headroom. Improve AOV or conversion rate before scaling spend.' };
    } else {
      verdict = { label: 'Losing money on ads', tone: 'bad', note: `You need at least ${breakEvenRoas.toFixed(2)}x ROAS to break even. Fix creative, offer or landing page before adding budget.` };
    }
  }

  const inputs = [
    { key: 'adSpend', label: 'Total Ad Spend', prefix: '$', step: 100, hint: 'What you spent on Meta, Google, TikTok, etc.' },
    { key: 'revenue', label: 'Revenue From Ads', prefix: '$', step: 100, hint: 'Sales attributed to those campaigns.' },
    { key: 'orders', label: 'Number Of Orders', prefix: '#', step: 1, hint: 'Orders generated by the campaigns.' },
    { key: 'cogsPercent', label: 'Product Cost (COGS)', prefix: '%', step: 1, hint: 'Cost of goods as a % of revenue.' },
    { key: 'otherCostPercent', label: 'Other Costs', prefix: '%', step: 1, hint: 'Shipping, payment fees, packaging as a % of revenue.' }
  ];

  const results = [
    { icon: TrendingUp, label: 'Your ROAS', value: `${roas.toFixed(2)}x`, sub: 'Revenue ÷ ad spend', accent: true },
    { icon: Target, label: 'Break-even ROAS', value: `${breakEvenRoas.toFixed(2)}x`, sub: `Based on ${grossMarginPercent}% contribution margin` },
    { icon: DollarSign, label: 'Net Profit', value: money(netProfit), sub: 'After product, other costs and ads', negative: netProfit < 0 },
    { icon: Percent, label: 'Net Margin', value: `${netMargin.toFixed(1)}%`, sub: 'Net profit as a share of revenue', negative: netMargin < 0 },
    { icon: ShoppingBag, label: 'Cost Per Order (CPA)', value: money2(cpa), sub: 'Ad spend ÷ orders' },
    { icon: DollarSign, label: 'Average Order Value', value: money2(aov), sub: 'Revenue ÷ orders' },
    { icon: DollarSign, label: 'Profit Per Order', value: money2(profitPerOrder), sub: 'Net profit ÷ orders', negative: profitPerOrder < 0 }
  ];

  return (
    <div className="roas-page">
      {/* Header */}
      <section className="roas-header">
        <div className="container">
          <span className="roas-badge">
            <Calculator size={14} />
            FREE TOOL
          </span>
          <h1 className="roas-title">Online ROAS Calculator</h1>
          <p className="roas-subtitle">
            Enter your ad spend, revenue and costs. We calculate your return on ad spend, your break-even ROAS and whether your campaigns actually make money.
          </p>
        </div>
      </section>

      {/* Calculator Inputs */}
      <section className="container roas-section">
        <div className="roas-card">
          <div className="roas-card-head">
            <h2>Your Numbers</h2>
            <button type="button" className="roas-reset" onClick={() => setV(DEFAULTS)}>
              <RotateCcw size={14} />
              Reset
            </button>
          </div>
          <div className="roas-inputs">
            {inputs.map((f) => (
              <label key={f.key} className="roas-field">
                <span className="roas-field-label">{f.label}</span>
                <span className="roas-input-wrap">
                  <span className="roas-input-prefix">{f.prefix}</span>
                  <input
                    type="number"
                    inputMode="decimal"
                    min="0"
                    step={f.step}
                    value={v[f.key]}
                    onChange={update(f.key)}
                  />
                </span>
                <span className="roas-field-hint">{f.hint}</span>
              </label>
            ))}
          </div>
        </div>
      </section>

      {/* Results (below the calculator) */}
      <section className="container roas-section roas-results-section">
        <div className={`roas-verdict roas-verdict-${verdict.tone}`}>
          <div className="roas-verdict-main">
            <div className="roas-verdict-kicker">RESULT</div>
            <div className="roas-verdict-label">{verdict.label}</div>
            <p className="roas-verdict-note">{verdict.note}</p>
          </div>
          <div className="roas-verdict-numbers">
            <div>
              <span>YOUR ROAS</span>
              <strong>{roas.toFixed(2)}x</strong>
            </div>
            <div>
              <span>BREAK-EVEN</span>
              <strong>{breakEvenRoas.toFixed(2)}x</strong>
            </div>
            <div>
              <span>NET PROFIT</span>
              <strong className={netProfit < 0 ? 'is-negative' : ''}>{money(netProfit)}</strong>
            </div>
          </div>
        </div>

        <div className="roas-results-grid">
          {results.map((r) => {
            const Icon = r.icon;
            return (
              <div key={r.label} className={`roas-result ${r.accent ? 'roas-result-accent' : ''}`}>
                <div className="roas-result-top">
                  <Icon size={18} />
                  <span>{r.label}</span>
                </div>
                <div className={`roas-result-value ${r.negative ? 'is-negative' : ''}`}>{r.value}</div>
                <div className="roas-result-sub">{r.sub}</div>
              </div>
            );
          })}
        </div>

        <div className="roas-formula">
          <strong>How it is calculated:</strong> ROAS = revenue ÷ ad spend. Break-even ROAS = 1 ÷ contribution margin, where contribution margin = 100% − product cost % − other costs %. Net profit = revenue × contribution margin − ad spend.
        </div>

        <div className="roas-cta">
          <p>Not hitting your break-even ROAS? We fix the creative, offer and funnel behind the number.</p>
          <button type="button" className="btn-primary" onClick={onOpenBooking}>
            <span>Book A Free Scaling Audit</span>
            <ArrowRight size={16} />
          </button>
        </div>
      </section>
    </div>
  );
}
